version: "3"
services:
  solr:
    container_name: solr
    image: solr:8.11.1
    env_file:
      - ./.ckan-env
    environment:
      - CKAN_CORE_NAME=${CKAN_CORE_NAME}
      - CKAN_VERSION=${CKAN_VERSION}
    volumes:
      - ${PWD}/solr8/ckan_init_solr.sh:/docker-entrypoint-initdb.d/ckan_init_solr.sh
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
